### ISSUE TITLE
pdf 질문

### ISSUE THREAD

**Issue by chanseobx** [ghks4098/DS_Project_3_2021#1]
1.
p.7 상단을 보면

"에러가 없는 경우 0(Success), 있는 경우 그에 맞는 에러 코드를 출력한다. (모든 명령어에 에러 코드가 출력되어야 한다한다.)"

이렇게 되어 있습니다.

하지만 p.16 동작결과를 보면 그렇지 않은데 제가 잘못 이해한 부분이 있을까요?
Print Format설명에는 부합해보입니다.

2.
p.8 ETC에서 ETC는 그 외 명령어를 말씀하시는 건가요?

에러코드가 0일 때 "결과 출력이 없는 명령어의 경우, Success와 에러코드 0 출력 (LOAD만 해당)"

이 말 뜻이 LOAD만 에러코드 0을 쓸 수 있다는 것 같은데, 1번과 충돌하지 않나 싶습니다.

3.
Result Manager::FindPathDfs(int startVertexKey, int endVertexKey)
이 함수에서 Dfs가 Bfs 오타이지 않을까 싶은데 함수 이름을 수정해도 괜찮을까요?

**Comment by ghks4098** [comment]
네 에러코드 0은 LOAD시에만 사용되며 
"에러가 없는 경우 0(Success), 있는 경우 그에 맞는 에러 코드를 출력한다. (모든 명령어에 에러 코드가 출력되어야 한다한다.)" 이 문장은 수정하도록 하겠습니다. 
Dfs 부분은 Bfs의 오타 인것 같네요 함수이름은 제가 수정할테니 일단은 BFS 코드로 짜시면 됩니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-11 (목) 09:44:44 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] pdf 질문 (Issue #1)
 



p.7 상단을 보면
"에러가 없는 경우 0(Success), 있는 경우 그에 맞는 에러 코드를 출력한다. (모든 명령어에 에러 코드가 출력되어야 한다한다.)"
이렇게 되어 있습니다.
하지만 p.16 동작결과를 보면 그렇지 않은데 제가 잘못 이해한 부분이 있을까요?
Print Format설명에는 부합해보입니다.



p.8 ETC에서 ETC는 그 외 명령어를 말씀하시는 건가요?
에러코드가 0일 때 "결과 출력이 없는 명령어의 경우, Success와 에러코드 0 출력 (LOAD만 해당)"
이 말 뜻이 LOAD만 에러코드 0을 쓸 수 있다는 것 같은데, 1번과 충돌하지 않나 싶습니다.



Result Manager::FindPathDfs(int startVertexKey, int endVertexKey)
이 함수에서 Dfs가 Bfs 오타이지 않을까 싶은데 함수 이름을 수정해도 괜찮을까요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chanseobx** [comment]
감사합니다.
