### ISSUE TITLE
질문이 있습니다.

### ISSUE THREAD

**Issue by kwYoohae** [ghks4098/DS_Project_3_2021#10]
질문이 있어서 연락드렸습니다.

1. ErrorCode에서 명령어에 인자가 부족한 경우는 오류코드를 출력하라 라고 명시되어있는데
`LOAD`명령어에 대해서 텍스트 파일이 존재하지 않은 경우는 있지만 인자에 대한 오류코드는 명시되어있지 않습니다.
`LOADREPORT` 명령어도 마찬가지 입니다.

2. `LOAD`, `LOADREPORT`명령어에 대해서는 특이하게 다음과 같이 `Success`를 출력하는 명령어가 있습니다.
![image](https://user-images.githubusercontent.com/74089271/142753363-8b506e49-f26e-448b-a173-ff9a0c3cbe13.png)
나머지 ErrorCode가 0인 `Success`상황에는 다음과 같이 `Success`를 출력해야하나요?
![image](https://user-images.githubusercontent.com/74089271/142753381-f2d1e551-5bbe-4936-9cf2-aca48702eee6.png)

3. `LOAD`나 `LOADREPORT`에서 `.txt`를 생략한 인자를 넣으면 못읽어 오는 것이 맞는지 궁금합니다.

**Comment by ghks4098** [comment]
1. Load에 대해서 text 파일이 없는 경우101 에러를 출력해주시면 됩니다.
 
2. Load해오는 명령어시에는 성공한 경우 에러코드 0을 출력해주셔야 합니다. 
 
3. 네 txt파일로 입력하셔야 합니다.
 
 
-----Original Message-----
From: "Yoo ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-21 (일) 16:25:06 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 질문이 있습니다. (Issue #10)
 
질문이 있어서 연락드렸습니다.

ErrorCode에서 명령어에 인자가 부족한 경우는 오류코드를 출력하라 라고 명시되어있는데
LOAD명령어에 대해서 텍스트 파일이 존재하지 않은 경우는 있지만 인자에 대한 오류코드는 명시되어있지 않습니다.
LOADREPORT 명령어도 마찬가지 입니다.

LOAD, LOADREPORT명령어에 대해서는 특이하게 다음과 같이 Success를 출력하는 명령어가 있습니다.

나머지 ErrorCode가 0인 Success상황에는 다음과 같이 Success를 출력해야하나요?

LOAD나 LOADREPORT에서 .txt를 생략한 인자를 넣으면 못읽어 오는 것이 맞는지 궁금합니다.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
