### ISSUE TITLE
main 함수 관련 질문입니다.

### ISSUE THREAD

**Issue by jeonmmingu** [ghks4098/DS_Project_3_2021#12]
![image](https://user-images.githubusercontent.com/93362949/142766192-a76ea7d1-e048-471d-a7b8-34aeb7e652e6.png)

1) main 함수에서 인자를 받는 이유가 무엇인지 이해가 잘 되지 않아 질문 남깁니다.
2) 또한 main 함수에서 if문의 용도를 잘 모르겠습니다.

문의 내용 읽어주셔서 감사합니다.

**Comment by ghks4098** [comment]
command.txt 파일을 받기 위함입니다.
컴파일시 char* 인자의 확인을 위함입니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-21 (일) 23:37:45 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] main 함수 관련 질문입니다. (Issue #12)
 

main 함수에서 인자를 받는 이유가 무엇인지 이해가 잘 되지 않아 질문 남깁니다.
또한 main 함수에서 if문의 용도를 잘 모르겠습니다.

문의 내용 읽어주셔서 감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
