### ISSUE TITLE
BFS구현 관련 질문입니다.(Stack.h , Queue.h)

### ISSUE THREAD

**Issue by jeonmmingu** [ghks4098/DS_Project_3_2021#13]
#Stack.h 과 Queue.h 에 대해 질문이 생겨 문의 남깁니다.

1. 올려주신 코드 중 Queue.h파일이 존재하는데 include 된 헤더 파일이나 소스 파일이 존재하지 않는 걸로 확인이 됩니다.  BFS구현 시 STL vector를 사용하려고 했는데 Queue.h파일이 존재하여 직접 구현하여 include 한 후 BFS에 이용해야 하는지 의문이 생겨 질문 남깁니다.

![image](https://user-images.githubusercontent.com/93362949/142796406-8c4a8453-f0c8-4ec5-8018-9b3fda14f992.png)

2. 또한 Stack.h파일의 주석을 읽어보면 stack과 queue를 하나의 class 안에서 구현해야 하는 것처럼 설명이 되어있는데 Stack만 구현하면 되는 건가요? 아니면 둘 다 구현해야 하는 건가요..?

**Comment by ghks4098** [comment]
아니요 stl vector 같은 필요한 stl 헤더 파일을 include 해서 구현하시면 됩니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-22 (월) 12:32:51 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] BFS구현 관련 질문입니다.(Stack.h , Queue.h) (Issue #13)
 
#Stack.h 과 Queue.h 에 대해 질문이 생겨 문의 남깁니다.

올려주신 코드 중 Queue.h파일이 존재하는데 include 된 헤더 파일이나 소스 파일이 존재하지 않는 걸로 확인이 됩니다. BFS구현 시 STL vector를 사용하려고 했는데 Queue.h파일이 존재하여 직접 구현하여 include 한 후 BFS에 이용해야 하는지 의문이 생겨 질문 남깁니다.


또한 Stack.h파일의 주석을 읽어보면 stack과 queue를 하나의 class 안에서 구현해야 하는 것처럼 설명이 되어있는데 Stack만 구현하면 되는 건가요? 아니면 둘 다 구현해야 하는 건가요..?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeonmmingu** [comment]
그럼 skeleton code에 있는 Queue.h와 Stack.h는 사용하지 않아도 되는 건가요??

**Comment by ghks4098** [comment]
네 사용하지 않으셔도 됩니다.
 
 
-----Original Message-----

**Comment by jeonmmingu** [comment]
넵 감사합니다.
