### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by kwYoohae** [ghks4098/DS_Project_3_2021#14]
구현중에 질문이 생겨서 연락드렸습니다.

1. 예제를 보면 다음과 같이 Course가 있는것으로 보입니다.
![image](https://user-images.githubusercontent.com/74089271/142800002-dc347d87-044f-4dac-b4c1-ff6f698d49e5.png)
하지만 Graph의 Vertex에 따로 각각의 위치 즉 `mapdata.txt` 이름 부분(?)
![image](https://user-images.githubusercontent.com/74089271/142800091-a83c5869-ab67-4657-a150-0fb014c9792b.png)

Course에 들어가야하는 Company(이름)부분을 넣을 변수가 `Vertex`에 변수로 존재하지 않은 것 같습니다.

혹시 어떻게 `Vertex`에서 각각의 이름을 불러올 수 있을까요?

2. STL을 사용하지 않고 기존에 있는 `Queue.h`, `Stack.h`, `Minheap.h`를 사용해서 구현해야 하나요>?

**Comment by ghks4098** [comment]
인덱스를 통해서 회사 이름을 불러오면 될 것 같네요 
 
-----Original Message-----
From: "Yoo ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-22 (월) 13:14:13 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 질문있습니다. (Issue #14)
 
구현중에 질문이 생겨서 연락드렸습니다.
예제를 보면 다음과 같이 Course가 있는것으로 보입니다.

하지만 Graph의 Vertex에 따로 각각의 위치 즉 mapdata.txt 이름 부분(?)
Course에 들어가야하는 Company(이름)부분을 넣을 변수가 Vertex에 변수로 존재하지 않은 것 같습니다.
혹시 어떻게 Vertex에서 각각의 이름을 불러올 수 있을까요?
읽어주셔서 감사합니다
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kwYoohae** [comment]
@ghks4098 인덱스를 통해서 회사 이름을 어떻게 불러오나요? 따로 Load할때 text파일 이름을 저장해서 
그 값을 통해서 파일입출력으로 가져와야 하나요?

**Comment by ghks4098** [comment]
따로 배열을 만드셔도 좋고, 인덱스와 회사이름을 튜플형태로 만들어 두셔도 좋고, 편하신 방법대로 구현하시면 될것같습니다.
 
-----Original Message-----

**Comment by kwYoohae** [comment]
@ghks4098 2번 질문도 답변 부탁드립니다

**Comment by ghks4098** [comment]
2번째 질문이 어디있나요?
 
-----Original Message-----

**Comment by kwYoohae** [comment]
@ghks4098 
![image](https://user-images.githubusercontent.com/74089271/142838129-70f73331-dc75-4ac5-a471-3b9d2a5e1016.png)
여기있습니다

**Comment by ghks4098** [comment]
직접 구현해서 사용하실 필요없이 STL을 사용하시면 됩니다. Queue.h를 사용하시지 않으시면 무시하고 구현만드시면 될 것 같습니다.
-----Original Message-----

**Comment by kwYoohae** [comment]
답변 감사드립니다 😄
