### ISSUE TITLE
Bellmanford

### ISSUE THREAD

**Issue by chanseobx** [ghks4098/DS_Project_3_2021#15]
음수사이클이 발생했을 경우
에러만 출력하나요?
아니면 에러를 출력하고 결과를 출력해야하나요?

**Comment by ghks4098** [comment]
에러만 출력해주시면 됩니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-22 (월) 15:51:24 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] Bellmanford (Issue #15)
 
음수사이클이 발생했을 경우
에러만 출력하나요?
아니면 에러를 출력하고 결과를 출력해야하나요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
