### ISSUE TITLE
제안서 Error code 관련 문의입니다.(200, 201)

### ISSUE THREAD

**Issue by jeonmmingu** [ghks4098/DS_Project_3_2021#16]
![image](https://user-images.githubusercontent.com/93362949/142836683-12e8938d-bd3e-47f9-8377-6dc5d01a4a74.png)

제안서 8페이지의 오류 처리 설명 부분에서 200번 오류와 201번 오류의 에러 명과 설명이 서로 바뀐 것 같은데 바꿔서 코드를 작성해도 괜찮을까요..?

<수정 예시>
vertexKeyNotExist  = 인자로 입력한 Vertex가 거래처의 거리 정보 데이터에 없는 경우
InvalidVertexKey = 명령어 인자(Vertex)가 잘못 들어간 경우

**Comment by ghks4098** [comment]
네 그럼 바꿔서 프로젝트 만드시고, 제가 수정하도록 하겠습니다.
github update 계속 살펴주시면 될 것같습니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-22 (월) 18:34:30 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 제안서 Error code 관련 문의입니다.(200, 201) (Issue #16)
 
제안서 8페이지의 오류 처리 설명 부분에서 200번 오류와 201번 오류의 에러 명과 설명이 서로 바뀐 것 같은데 바꿔서 코드를 작성해도 괜찮을까요..?
<수정 예시>
vertexKeyNotExist = 인자로 입력한 Vertex가 거래처의 거리 정보 데이터에 없는 경우
InvalidVertexKey = 명령어 인자(Vertex)가 잘못 들어간 경우
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeonmmingu** [comment]
감사합니다.
