### ISSUE TITLE
Dijkstra 질문

### ISSUE THREAD

**Issue by chanseobx** [ghks4098/DS_Project_3_2021#2]
Bfs 구현
1. pdf 3page를 보면 "음수인 간선이 있으면 제거하고 최단거리를 구한다. " 고 되어 있는데 에러를 출력하고 구하면 되는것인가요?

Dijkstra 구현

2. minheap을 이용해서 구현하는 함수를 삭제하신 것 같은데 그러면 minheap.h을 이용하지 않는 것인가요? 아니면 set을 이용하면서 minheap을 이용해야 하는건가요?
3. 어떤식으로 작동되는지 감이 안오는데 보충 설명 해주실 수 있나요? visited, unvisited 변수도 어디에 사용해야할지 모르겠습니다. 방문한 정점과 방문하지 않은 정점을 구분하는 것은 알고 있습니다.

**Comment by ghks4098** [comment]
1. 네 음수인 간선이 있으면 에러를 출력하고 음수 간선을 제거하고 최단거리를 구하시면 됩니다.
 
2. 깃허브의 minheap은 삭제할 것이니까 무시하고 진행하시면 될 것 같습니다. 
 
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-14 (일) 16:44:07 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] Dijkstra 질문 (Issue #2)
 
Bfs 구현

pdf 3page를 보면 "음수인 간선이 있으면 제거하고 최단거리를 구한다. " 고 되어 있는데 에러를 출력하고 구하면 되는것인가요?

Dijkstra 구현
2. minheap을 이용해서 구현하는 함수를 삭제하신 것 같은데 그러면 minheap.h을 이용하지 않는 것인가요? 아니면 set을 이용하면서 minheap을 이용해야 하는건가요?
3. 어떤식으로 작동되는지 감이 안오는데 보충 설명 해주실 수 있나요? visited, unvisited 변수도 어디에 사용해야할지 모르겠습니다. 방문한 정점과 방문하지 않은 정점을 구분하는 것은 알고 있습니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chanseobx** [comment]
@ghks4098 utility 헤더파일을 사용해도 되나요?
