### ISSUE TITLE
bellmanford 관련 질문

### ISSUE THREAD

**Issue by chanseobx** [ghks4098/DS_Project_3_2021#20]
pdf보면 인자가 오류일 경우 에러를 출력하라고 되어 있는데
인자가 필요한가요?
동작 예시에도 인자가 없는것 같아 질문 드립니다.

**Comment by ghks4098** [comment]
인자가 없이 돌아가는 함수라서 인자가 들어가는 경우 에러메세지를 출력해야합니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-23 (화) 09:55:04 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] bellmanford 관련 질문 (Issue #20)
 
pdf보면 인자가 오류일 경우 에러를 출력하라고 되어 있는데
인자가 필요한가요?
동작 예시에도 인자가 없는것 같아 질문 드립니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
