### ISSUE TITLE
BellmanFord 동작 예시 관련 질문입니다.

### ISSUE THREAD

**Issue by jeonmmingu** [ghks4098/DS_Project_3_2021#21]
![image](https://user-images.githubusercontent.com/93362949/142972406-ccfee01e-06ce-409d-92d8-9113022a0652.png)
[제안서 15pg]

Q) 벨만포드 알고리즘으로 해당 그래프의 최단 거리를 구할 시, 음수 간선을 포함하기 때문에 아래와 같이 나오는게 맞지 않나요..?

![image](https://user-images.githubusercontent.com/93362949/142972539-9690578d-4cf3-4b7a-9767-99b78ef48752.png)

문의 내용 읽어주셔서 감사합니다.

**Comment by ghks4098** [comment]
네 0 1 6이 맞습니다
제가 예시를 잘 못 썻더라고요 빨리 수정하겠습니다.
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-23 (화) 13:48:22 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] BellmanFord 동작 예시 관련 질문입니다. (Issue #21)
 

[제안서 15pg]
Q) 벨만포드 알고리즘으로 해당 그래프의 최단 거리를 구할 시, 음수 간선을 포함하기 때문에 아래와 같이 나오는게 맞지 않나요..?
문의 내용 읽어주셔서 감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeonmmingu** [comment]
감사합니다.
