### ISSUE TITLE
에러명이 헷갈려 질문드립니다.

### ISSUE THREAD

**Issue by nicekim2000** [ghks4098/DS_Project_3_2021#22]
오류명 출력하는데 헷갈리는 부분이 있어 질문드립니다.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/90180909/143079657-1b39cca9-354a-41c2-bf20-3079a7f7a4b7.png">

위와 같은 에러는 "command.txt"에서 입력 받은 명령어에 잘못된 인자가 있을 시 출력하는 것이고

<img width="452" alt="image" src="https://user-images.githubusercontent.com/90180909/143079794-f9fe2f68-71a0-43ea-8e3a-5cc774a4bd29.png">

위와 같은 오류는 명령어 실행 결과 Our Company에서 Target Company 까지의 경로가 없을 시 출력 되는 에러인 것이 맞는 건가요?

에러코드 200과 201이 수정되었는데 아래 와 같이 pdf 의 동작 예시의  "log.txt" 도 수정되어야 할 것 같습니다.
<img width="206" alt="image" src="https://user-images.githubusercontent.com/90180909/143080541-dc84b7e9-2d51-47a7-a6a8-759aa7497691.png">

"Result.h" 또한 수정되어야 할 것 같습니다.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/90180909/143080892-322d6db1-fa16-43b8-808a-2df8359031c4.png">

**Comment by ghks4098** [comment]
아 넵 아직 pdf만 수정한것 같네요, 헤더와 log.txt 예시도 금방 수정하도록 하겠습니다.
 
 200은 이해하신데로 명령어 잘못되게 인자가 들어오시면 출력하시면 되고, 201은 경로가 없거나 하는식으로 잘못되게 거리 정보가 만들어졌을 때 출력하시면 됩니다.
 
-----Original Message-----
From: "jaehyuk ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-24 (수) 03:13:27 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 에러명이 헷갈려 질문드립니다. (Issue #22)
 
오류명 출력하는데 헷갈리는 부분이 있어 질문드립니다.
위와 같은 에러는 "command.txt"에서 입력 받은 명령어에 잘못된 인자가 있을 시 출력하는 것이고
위와 같은 오류는 명령어 실행 결과 Our Company에서 Target Company 까지의 경로가 없을 시 출력 되는 에러인 것이 맞는 건가요?
에러코드 200과 201이 수정되었는데 아래 와 같이 pdf 의 동작 예시의 "log.txt" 도 수정되어야 할 것 같습니다.
"Result.h" 또한 수정되어야 할 것 같습니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nicekim2000** [comment]
답변 감사드립니다.
