### ISSUE TITLE
다익스트라 동작 예시관련 질문입니다.

### ISSUE THREAD

**Issue by nicekim2000** [ghks4098/DS_Project_3_2021#23]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/90180909/143191578-41e36af6-3768-47da-bf09-b61ad4e91e36.png">

BFS시 음수인 간선이 포함되면 다음 사진과 같이 에러 코드 203까지 출력하게 되어있습니다.

 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/90180909/143191862-3dbd3d70-39fb-44da-ab1c-e67f9e295726.png">

다익스트라 실행시 음수인 간선이 포함되면 에러 코드 203는 출력 안 해도 되는 건가요 ?

**Comment by ghks4098** [comment]
다익스트라 실행시에도 동일하게 
에러코드 203 출력해야 합니다.
 
BFS랑 동일한 포멧으로 출력되어야 합니다.
 
 
-----Original Message-----
From: "jaehyuk ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-24 (수) 16:14:56 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 다익스트라 동작 예시관련 질문입니다. (Issue #23)
 
BFS시 음수인 간선이 포함되면 다음 사진과 같이 에러 코드 203까지 출력하게 되어있습니다.
다익스트라 실행시 음수인 간선이 포함되면 에러 코드 203는 출력 안 해도 되는 건가요 ?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nicekim2000** [comment]
pdf 동작 예시에서 는 출력이 안되어있어 질문 드렸습니다. 답변 감사드립니다.
