### ISSUE TITLE
Floyd 알고리즘

### ISSUE THREAD

**Issue by chanseobx** [ghks4098/DS_Project_3_2021#25]
Floyd 알고리즘 실행시 음의 사이클이 존재하면 안되는 것으로 알고 있는데
에러 출력하는 예시가 없어 보입니다.

음의 사이클이 존재해도 상관 없나요?

**Comment by ghks4098** [comment]
벨만포드와 동일하게 에러 204로 추가하도록 하겠습니다
감사합니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-25 (목) 13:27:53 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] Floyd 알고리즘 (Issue #25)
 
Floyd 알고리즘 실행시 음의 사이클이 존재하면 안되는 것으로 알고 있는데
에러 출력하는 예시가 없어 보입니다.
음의 사이클이 존재해도 상관 없나요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
