### ISSUE TITLE
에러코드 질문드립니다.

### ISSUE THREAD

**Issue by Jae211** [ghks4098/DS_Project_3_2021#29]
LOADREPORT의 에러코드, 에러명이 각각 005, FailedtoUpdatePath가 맞나요?
Result.h에도 해당 에러 관련 코드가 없고 파일 자체가 존재하지 않는 경우이기 때문에 LoadFileNotExist가 적절한 것 같아 질문 드립니다.

감사합니다.

**Comment by Jae211** [comment]
RABINKARP의 InvalidOptionNumber 에러의 경우에도 Result.h에 입력되어있지 않은데, 직접 입력해서 사용하면 되나요??

**Comment by ghks4098** [comment]
넵 직접 입력해서 사용하시면 될것 같습니다.
 
 
-----Original Message-----

**Comment by ghks4098** [comment]
Result.h에 추가해서 사용하시면 될것 같습니다. 넵 원래의 pdf 내용대로 FailedtoUpdatePath로 하셔도 감점은 없을 예정입니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-26 (금) 19:54:53 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 에러코드 질문드립니다. (Issue #29)
 
LOADREPORT의 에러코드, 에러명이 각각 005, FailedtoUpdatePath가 맞나요?
Result.h에도 해당 에러 관련 내용 코드가 없고 파일 자체가 존재하지 않는 경우이기 때문에 LoadFileNotExist가 적절한 것 같아 질문 드립니다.
감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
