### ISSUE TITLE
질문입니다.

### ISSUE THREAD

**Issue by kwYoohae** [ghks4098/DS_Project_3_2021#3]
1. `Manger.cpp`에 `Result Manager::FindPathDfs(int startVertexKey, int endVertexKey)`와 같은 함수가 있는데
`DFS`도 사용해야 하는 것 인가요?
2.  `Manger.cpp`의 변수인 `ERROR_LOG_PATH`는 뭘 담아야 할까요? 기존에 있는 `RESULT_LOG_PATH `와 같이 `log.txt`를 담아야하나요?
3. 만약 `RabinKarp`알고리즘에서 텍스트 파일을 읽어올 때 `char` 배열로 읽어온다면 문자 길이 제한이 있을까요? 아니면 `string`으로 읽어야할까요? 
만약 `string`으로 읽어오면 메서드의 인자의 타입이 `const char *`던데 `string`과 호환이 가능한가요? 형변환을 해줘야하나요?

읽어주셔서 감사합니다.

**Comment by ghks4098** [comment]
1. 아 제가 코드에 있는 DFS라고 적혀있는 오타 부분은 다 BFS로 수정했을 겁니다. 만약에 DFS라고 적혀있어도 BFS를 구현해주시면 됩니다.
2. 같이 LOG.TXT 파일에 담으시면 됩니다.
3. RABINKRAP 알고리즘 구현시 문자 길이 제한은 10글자 제한으로 하였습니다. const char, string 호환을 위한 함수도 있고, 형변환 하면서 사용할 수 있는것으로 알고있습니다.
 
-----Original Message-----
From: "Yoo ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-15 (월) 14:43:20 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 질문입니다. (Issue #3)
 

Manger.cpp에 Result Manager::FindPathDfs(int startVertexKey, int endVertexKey)와 같은 함수가 있는데
DFS도 사용해야 하는 것 인가요?
Manger.cpp의 변수인 ERROR_LOG_PATH는 뭘 담아야 할까요? 기존에 있는 RESULT_LOG_PATH 와 같이 log.txt를 담아야하나요?
만약 RabinKarp알고리즘에서 텍스트 파일을 읽어올 때 char 배열로 읽어온다면 문자 길이 제한이 있을까요? 아니면 string으로 읽어야할까요?
만약 string으로 읽어오면 메서드의 인자의 타입이 const char *던데 string과 호환이 가능한가요? 형변환을 해줘야하나요?

읽어주셔서 감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kwYoohae** [comment]
답변 감사드립니다!!
