### ISSUE TITLE
BFS, Dijstra 음수간선 에러와 명령 인자에 관한 질문

### ISSUE THREAD

**Issue by Merry-Berry** [ghks4098/DS_Project_3_2021#30]
안녕하세요, 에러 출력과 처리 로직에서 질문이 있습니다.

1. BFS와 Dijkstra에서 에러를 출력하는 상황이 "음수인 간선이 존재할 때"인지, "음수 사이클이 존재할 때"인지 궁금합니다.
아래 설명은 "음수 사이클이 발생하면, 음수 간선을 배제하고 최단 경로를 구한다"고 이해하였고,
![image](https://user-images.githubusercontent.com/55453184/143777344-01b1db62-4f8c-49d1-8bfe-cf6c5d7b77aa.png)
이 설명의 경우 "음수 간선이 존재하면, 음수 간선을 배제하고 최단 경로를 구한다"고 이해했습니다.
![image](https://user-images.githubusercontent.com/55453184/143777381-5a8f4732-2ecb-4de6-b518-666f80f6f9cd.png)

2. "명령어에 인자(Parameter)가 부족한 경우 오류 코드를 출력한다."고 명시되어 있습니다. 그러나 인자가 많은 경우에 대한 오류 코드는 따로 있는데, 인자가 부족할 때 출력하는 오류 코드는 제안서에서 못 찾겠습니다. LOAD나 RABINKARP와 같이 인자를 받는 명령에서 인자가 부족한 경우 어떤 에러 코드를 사용하는지 궁금합니다.

**Comment by Merry-Berry** [comment]
3. 인자가 많을 때 사용하는 에러 코드(InvalidOptionNumber)는 RABINKARP 명령에만 있습니다. 다른 명령에서 인자가 많을 때 어떤 오류 코드를 사용하는지도 궁금합니다.
![image](https://user-images.githubusercontent.com/55453184/143778014-0b2e69bf-e587-4f58-a16a-7ad0a7b1cec9.png)

**Comment by ghks4098** [comment]
그래프 알고리즘에 대한 인자가 많은 경우에 대한 오류코드는 에러코드 200, 인자가 잘못 들어간 경우로 생각하시면 됩니다.
 
 
-----Original Message-----

**Comment by ghks4098** [comment]
BFS와 다익스트라는 음수 간선이 존재하는 경우에 돌아가는 알고리즘이 아니기 때문에, 음수 간선이 존재하기만 하는 상황을 생각하시면 됩니다.
 
라빈카프에서 인자가 없는 경우는 생각하시지 않으셔도 될 것 같고, LOAD에서도 텍스트 파일이 존재하지 않는 경우만 생각하시면 될 것 같습니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-29 (월) 01:50:43 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] BFS, Dijstra 음수간선 에러와 명령 인자에 관한 질문 (Issue #30)
 
안녕하세요, 에러 출력과 처리 로직에서 질문이 있습니다.

BFS와 Dijkstra에서 에러를 출력하는 상황이 "음수인 간선이 존재할 때"인지, "음수 사이클이 존재할 때"인지 궁금합니다.
아래 설명은 "음수 사이클이 발생하면, 음수 간선을 배제하고 최단 경로를 구한다"고 이해하였고,

이 설명의 경우 "음수 간선이 존재하면, 음수 간선을 배제하고 최단 경로를 구한다"고 이해했습니다.

"명령어에 인자(Parameter)가 부족한 경우 오류 코드를 출력한다."고 명시되어 있습니다. 그러나 인자가 많은 경우에 대한 오류 코드는 따로 있는데, 인자가 부족할 때 출력하는 오류 코드는 제안서에서 못 찾겠습니다. LOAD나 RABINKARP와 같이 인자를 받는 명령에서 인자가 부족한 경우 어떤 에러 코드를 사용하는지 궁금합니다.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Merry-Berry** [comment]
감사합니다. :)
