### ISSUE TITLE
RabinKarp 에러 관련 질문입니다.

### ISSUE THREAD

**Issue by jeonmmingu** [ghks4098/DS_Project_3_2021#31]
![image](https://user-images.githubusercontent.com/93362949/143788498-1e2cca7d-75ad-4be7-85aa-a0f9d861214f.png)

제안서 9page에 나오는 RabinKarp명령어에 대한 에러설명 부분에서 이해가 잘 안되어 문의 남깁니다.

Q) RABINKARP명령어의 경우 예시를 들어주신 것처럼 입력 인자에 "big data"와 같이 띄어쓰기가 포함될 수 있는데 인자가 많이 들어온 경우에 대한 에러를 처리할 수 있나요?

![image](https://user-images.githubusercontent.com/93362949/143788650-8a12e25e-e54d-4f9f-bce6-58dbbaad585b.png)

**Comment by ghks4098** [comment]
여기서 인자가 많이 들어왔다는 의미는 10글자 이상의 인자가 들어온 경우로 생각하시면 됩니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-29 (월) 07:28:55 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] RabinKarp 에러 관련 질문입니다. (Issue #31)
 
제안서 9page에 나오는 RabinKarp명령어에 대한 에러설명 부분에서 이해가 잘 안되어 문의 남깁니다.
Q) RABINKARP명령어의 경우 예시를 들어주신 것처럼 입력 인자에 "big data"와 같이 띄어쓰기가 포함될 수 있는데 인자가 많이 들어온 경우에 대한 에러를 처리할 수 있나요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeonmmingu** [comment]
넵 감사합니다.
