### ISSUE TITLE
FLOYD 질문입니다.

### ISSUE THREAD

**Issue by nicekim2000** [ghks4098/DS_Project_3_2021#33]
pdf 16page 에서 플로이드 결과가 아래와 같습니다.
<img width="118" alt="image" src="https://user-images.githubusercontent.com/90180909/143829247-a5311366-019d-413d-aa11-731571e0e95c.png">
아래와 같은 결과가 나와야 되는 것 아닌가요 ?
<img width="184" alt="image" src="https://user-images.githubusercontent.com/90180909/143829311-4f377851-8213-4f01-8f33-2a06e40cbfbb.png">

질문하였으나 답변을 받지 못해 다시 질문합니다.

**Comment by ghks4098** [comment]
아 죄송합니다.
pdf log 결과의 답은 오류가 있습니다.
넵 아래처럼 나오는게 정상 연산 결과입니다.
 
-----Original Message-----
From: "jaehyuk ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-29 (월) 17:03:10 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] FLOYD 질문입니다. (Issue #33)
 
pdf 16page 에서 플로이드 결과가 아래와 같습니다.

아래와 같은 결과가 나와야 되는 것 아닌가요 ?
질문하였으나 답변을 받지 못해 다시 질문합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghks4098** [comment]
pdf의 결과부분을 수정하였으니 한번 비교해보시면 좋을 것 같습니다.
 
-----Original Message-----
From: "jaehyuk ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-29 (월) 17:03:10 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] FLOYD 질문입니다. (Issue #33)
 
pdf 16page 에서 플로이드 결과가 아래와 같습니다.

아래와 같은 결과가 나와야 되는 것 아닌가요 ?
질문하였으나 답변을 받지 못해 다시 질문합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nicekim2000** [comment]
확인하였습니다 . 감사합니다.
