### ISSUE TITLE
Rabinkarp 동작 예시 질문있습니다.

### ISSUE THREAD

**Issue by jiwoo0629** [ghks4098/DS_Project_3_2021#34]
![image](https://user-images.githubusercontent.com/90768869/144173747-f0154f93-cfcb-4f54-b770-82cdd55b5cf6.png)
위의 예시에서 RABINKARP healthcare를 했을 경우, 입력 인자가 10글자 이상이기 때문에 InvalidOptionNumber의 에러를 출력해야 한다고 생각했는데
![image](https://user-images.githubusercontent.com/90768869/144173868-13af4616-834e-48cc-aeb0-bc2aac7bac5e.png)
pdf의 예시에는 NO DUPLICATE TITLE EXISTS를 출력했습니다.
InvalidOptionNumber 에러를 출력하는 기준이 10글자 이상인지 10글자 초과인지 알고싶습니다.

**Comment by ghks4098** [comment]
healthcare는 동일한 단어가 없어서 탐지가 안된 것이고, 10글자 이상이면 에러메세지가 출력되어야 합니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-01 (수) 13:51:54 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] Rabinkarp 동작 예시 질문있습니다. (Issue #34)
 

위의 예시에서 RABINKARP healthcare를 했을 경우, 입력 인자가 10글자 이상이기 때문에 InvalidOptionNumber의 에러를 출력해야 한다고 생각했는데

pdf의 예시에는 NO DUPLICATE TITLE EXISTS를 출력했습니다.
InvalidOptionNumber 에러를 출력하는 기준이 10글자 이상인지 10글자 초과인지 알고싶습니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiwoo0629** [comment]
healthcare도 알파벳으로 10글자인데 그렇다면 10글자 이상으로 생각할 수 있지 않나요??

**Comment by ghks4098** [comment]
아 healthcare가 9글자 인줄 알았네요 구현하실때 10글자 이상으로 구현하시면 됩니다
healthcare가 오류가 나와야 정상이겠네요
 
-----Original Message-----

**Comment by jiwoo0629** [comment]
네 감사합니다!!
