### ISSUE TITLE
Graph 클래스 관련 질문있습니다.

### ISSUE THREAD

**Issue by jiwoo0629** [ghks4098/DS_Project_3_2021#35]
![image](https://user-images.githubusercontent.com/90768869/144175154-e4c128c7-5d96-46ad-9cd4-e6ec9b3f427e.png)
Manager.cpp를 구현할 때 Graph 클래스에 존재하는 4개의 vector를 필수로 사용하여 구현해야 하는 것인지 알고 싶습니다.

**Comment by ghks4098** [comment]
사용하실 필요가 없으시면 반드시 사용해서 구현하실 필요는 없습니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-01 (수) 14:05:56 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] Graph 클래스 관련 질문있습니다. (Issue #35)
 

Manager.cpp를 구현할 때 Graph 클래스에 존재하는 4개의 vector를 필수로 사용하여 구현해야 하는 것인지 알고 싶습니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
