### ISSUE TITLE
프로젝트에 질문 있습니다.

### ISSUE THREAD

**Issue by quad0214** [ghks4098/DS_Project_3_2021#37]
안녕하세요. 컴퓨터정보공학부 2020202094학번 백종천입니다.

프로젝트와 관련하여 질문이 많아 아래와 같이 항목으로 작성한 점 양해부탁드립니다.

- 명령 공통 질문
    1. 길찾기 명령과 라빈 카프 명령을 제외하고, 명령의 개수가 모자르거나 넘치는 경우 어떤 오류를 출력하여야 되나요?
    
- LOAD
    1. 인자로 제공되는 텍스트 파일에서 거래처 이름과 weight들은 띄어쓰기, /, 띄어쓰기를 반드시 사이에 두고 작성되어있나요? 띄어쓰기가 없이 '/'만 작성되어있을 수도 있는 지 궁금합니다

- BFS
    1. 제안서 5페이지의 명령어 사용 예 및 기능을 보면 BFS 명령 설명 중에 "DFS를 수행하고..."와 같은 내용이 나와있습니다. 잘못 작성된 것인가요?
    2. cpp 파일 중에 BFS가 아니라 DFS로 작성된 함수명 들이 존재하는 데 오타인 건 가요?
    3. 제안서 11페이지의 BFS 출력 예시를 보면, Course 항목만 띄어쓰기, :, 띄어쓰기로 출력되고 있습니다. "Course: "와 같이 출력하여도 되나요? 또한 이런 세세한 출력 부분으로 인해 감점요소가 될 수 있는 지 궁금합니다.
    4. 제안서 15 페이지의 동작 예시에서 "BFS 1 3" 명령 출력을 보면, VertexKeyNotExist 오류가 200 에러 코드로 출력되었습니다. 이때, BFS 명령과 모든 길찾기 명령은 인자를 전혀 갖지 않는데 해당 오류가 존재하는 이유를 모르겠습니다. 그리고 또한 해당 오류의 번호는 201번 인데 200으로 출력된 것을 볼 수 있습니다.
     따라서 VertexKeyNotExist 오류가 왜 존재하는 지 여쭤보고 싶으며, 위 경우는 InvalidVertexKey 오류가 출력되는 것이 맞지 않는가 여쭤보고 싶습니다.
    5.  처음에 주어지는 그래프 정보 혹은 음수 간선을 제거한 그래프 정보에서 Our Company와 Target Company는 항상 연결되어있다고 가정하나요?
    
- Floyd, Bellman Ford
    1. Floyd와 Bellman Ford 방법을 통해 shortest path를 구하는 메서드에 bool형 매개변수를 추가하여 음수 사이클의 경우 true를 갖도록 구현하여도 되나요?
    
- 라빈 카프
    1. 라빈 카프 명령이 실행되기 전에 무조건 LOADREPORT 명령이 실행된다고 가정하나요?
    2. 레포트 파일은 프로그램 실행 중간에 삭제 안 된다고 가정하나요?
    3. 인자를 10글자 이내로 제한한다고 하였는데, 이때 10글자도 포함되는 것인가요?
    4. 인자로 받는 텍스트 파일내에 제목들은 어떤 문자를 사이에 두고 존재하는 지 궁금합니다. 예시를 보면 단순히 개행으로 각 제목을 구분한 것인지 혹은 두 개 이상의 개행을 이용한 것인지 헷갈려 질문드렸습니다.
    5. Manager에 정의된 라빈 카프 함수의 경우, 하나의 문자열 속에서 찾고자 하는 문자열이 있는 지 검색하는 용도라고 이해했습니다. 이에 문자열 속 찾고자 하는 문자열 있다면 이를 알리기 위하여 bool 형 매개변수를 추가해도 되는 지 궁금합니다.
    
- 그 외
    1. 코드에는 ferr와 관련된 변수들이 존재하는 데, 제안서에서 이를 언급하지 않은 것 같습니다. 무시하고 프로젝트 진행하면 되나요?
    2. 스켈레톤 코드에 정의되지 않은 필드 변수들을 추가로 선언하여 사용하여도 되나요?
    3. Manager 헤더에 min heap과 관련된 다익스트라 함수가 있는데 제안서에 해당 내용이 나와있지 않는 것 같습니다. 무시하고 구현하여도 되나요?
    4. 과제 제안서 5 페이지에 LOADREPORT 명령 사용법에 LOAD로 오타가 존재합니다.
    5. 과제 제안서 5 페이지에 DIJKSTRA 명령이 DIJKKSTRA로 작성되어있는 오타가 존재합니다.
    6. 과제 제안서 7페이지, 오류명 FaildtoUpdatePath에 오타가 존재하는 것 같습니다. 과제를 수행할 때는 FailedtoUpdataPath로 바꾸어 진행해도 되는 지 궁금합니다.
    7. 과제 제안서 7페이지 오류 코드를 나타내는 표에서 서로 다른 명령의 오류인 것 같은 오류들이 5번째 행에 하나인 것 처럼 표현되고 있습니다. InvalidAlgorithm의 경우 BFS, DIJKSTRA만의 오류, NegativeCycleDetected는 BELLMANFORD, FLOYD만의 오류라고 이해하면 되나요?
    8. 제공되는 텍스트 파일에 빈줄이 존재하는 경우가 있나요? 이런 경우 어떻게 처리해주어야 하나요?
    9. 추가적인 정보 없이 오류 메시지만을 출력하는 종류의 오류일 경우 다음과 같이 출력하면 되나요?
    ===== <오류명> =====
    Error code: <오류 코드>
    =================
    10. 한 명령의 출력을 마친 뒤에는 두 번 개행하는 지 궁금합니다. 또한 LOAD와 같이 오류메시지와 성공 메시지를 동시에 출력하는 명령의 경우 오류 메시지와 성공 메시지 사이도 두 번 개행하는 지 궁금합니다
        
 ![image](https://user-images.githubusercontent.com/34961209/144529062-ff5a12e1-d5f3-4475-bb67-4a41cd0f98d3.png)
        
    
질문 읽어주셔서 감사합니다.

**Comment by ghks4098** [comment]
길찾기 명령시 인자가 필요없게 구현할 수 있으니 인자가 잘못들어간 경우에 대해서 200 출력하시면 될 것 같습니다.
띄어쓰기, /, 띄어쓰기를 두고 작성하셔야 합니다 
제안서와 스켈레톤 코드에서의 DFS부분은 모두 오타입니다.
세세한 출력에 대해서의 감점은 없습니다.
VertexKeyNotExist 에러는 경우가 없다고 생각되어 구현하지 않으셔도 감점은 없습니다. 
 
BOOL형 매개변수 추가해서 구현하셔도 됩니다.
 
무조건 LOADREPORT 명령이 실행된다고 가정하고,
인자를 10글자 이내로 제한한다고 하였는데, 이 내용은 헷갈릴수 있어 11글자로 하셔도 문제 없습니다.
두번의 개행으로 문자열을 구분하였습니다.
Manager에 정의된 라빈 카프 함수의 경우, 하나의 문자열 속에서 찾고자 하는 문자열이 있는 지 검색하는 용도라고 이해했습니다. 이에 문자열 속 찾고자 하는 문자열 있다면 이를 알리기 위하여 bool 형 매개변수를 추가해도 되는 지 궁금합니다. 여기서도 추가 가능합니다.

코드에는 ferr와 관련된 변수들이 존재하는 데, 제안서에서 이를 언급하지 않은 것 같습니다. 무시하고 프로젝트 진행하면 되나요?
무시하고 진행하시면 됩니다

스켈레톤 코드에 정의되지 않은 필드 변수들을 추가로 선언하여 사용하여도 되나요?
변수들의 추가 선언은 자유입니다.

Manager 헤더에 min heap과 관련된 다익스트라 함수가 있는데 제안서에 해당 내용이 나와있지 않는 것 같습니다. 무시하고 구현하여도 되나요?
minheap은 제거하시고 하셔도 됩니다.

과제 제안서 5 페이지에 LOADREPORT 명령 사용법에 LOAD로 오타가 존재합니다.
과제 제안서 5 페이지에 DIJKSTRA 명령이 DIJKKSTRA로 작성되어있는 오타가 존재합니다.
감사합니다. 

과제 제안서 7페이지, 오류명 FaildtoUpdatePath에 오타가 존재하는 것 같습니다. 과제를 수행할 때는 FailedtoUpdataPath로 바꾸어 진행해도 되는 지 궁금합니다.
내 수정하고 구현하세요

과제 제안서 7페이지 오류 코드를 나타내는 표에서 서로 다른 명령의 오류인 것 같은 오류들이 5번째 행에 하나인 것 처럼 표현되고 있습니다. InvalidAlgorithm의 경우 BFS, DIJKSTRA만의 오류, NegativeCycleDetected는 BELLMANFORD, FLOYD만의 오류라고 이해하면 되나요?
네 맞습니다

제공되는 텍스트 파일에 빈줄이 존재하는 경우가 있나요? 이런 경우 어떻게 처리해주어야 하나요?
빈줄은 없다고 가정하시고 구현하시면 됩니다

추가적인 정보 없이 오류 메시지만을 출력하는 종류의 오류일 경우 다음과 같이 출력하면 되나요?
===== <오류명> =====
Error code: <오류 코드>
=================
저런식으로 출력하시면 될 것 같습니다

한 명령의 출력을 마친 뒤에는 두 번 개행하는 지 궁금합니다. 또한 LOAD와 같이 오류메시지와 성공 메시지를 동시에 출력하는 명령의 경우 오류 메시지와 성공 메시지 사이도 두 번 개행하는 지 궁금합니다
둘다 상관 없을 것 같습니다.


 
 
 
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-03 (금) 10:28:49 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 프로젝트에 질문 있습니다. (Issue #37)
 
안녕하세요. 컴퓨터정보공학부 2020202094학번 백종천입니다.
프로젝트와 관련하여 질문이 많아 아래와 같이 항목으로 작성한 점 양해부탁드립니다.

명령 공통 질문

길찾기 명령과 라빈 카프 명령을 제외하고, 명령의 개수가 모자르거나 넘치는 경우 어떤 오류를 출력하여야 되나요?


LOAD

인자로 제공되는 텍스트 파일에서 거래처 이름과 weight들은 띄어쓰기, /, 띄어쓰기를 반드시 사이에 두고 작성되어있나요? 띄어쓰기가 없이 '/'만 작성되어있을 수도 있는 지 궁금합니다


BFS

제안서 5페이지의 명령어 사용 예 및 기능을 보면 BFS 명령 설명 중에 "DFS를 수행하고..."와 같은 내용이 나와있습니다. 잘못 작성된 것인가요?
cpp 파일 중에 BFS가 아니라 DFS로 작성된 함수명 들이 존재하는 데 오타인 건 가요?
제안서 11페이지의 BFS 출력 예시를 보면, Course 항목만 띄어쓰기, :, 띄어쓰기로 출력되고 있습니다. "Course: "와 같이 출력하여도 되나요? 또한 이런 세세한 출력 부분으로 인해 감점요소가 될 수 있는 지 궁금합니다.
제안서 15 페이지의 동작 예시에서 "BFS 1 3" 명령 출력을 보면, VertexKeyNotExist 오류가 200 에러 코드로 출력되었습니다. 이때, BFS 명령과 모든 길찾기 명령은 인자를 전혀 갖지 않는데 해당 오류가 존재하는 이유를 모르겠습니다. 그리고 또한 해당 오류의 번호는 201번 인데 200으로 출력된 것을 볼 수 있습니다.
따라서 VertexKeyNotExist 오류가 왜 존재하는 지 여쭤보고 싶으며, 위 경우는 InvalidVertexKey 오류가 출력되는 것이 맞지 않는가 여쭤보고 싶습니다.


Floyd, Bellman Ford

Floyd와 Bellman Ford 방법을 통해 shortest path를 구하는 메서드에 bool형 매개변수를 추가하여 음수 사이클의 경우 true를 갖도록 구현하여도 되나요?


라빈 카프

라빈 카프 명령이 실행되기 전에 무조건 LOADREPORT 명령이 실행된다고 가정하나요?
레포트 파일은 프로그램 실행 중간에 삭제 안 된다고 가정하나요?
인자를 10글자 이내로 제한한다고 하였는데, 이때 10글자도 포함되는 것인가요?
인자로 받는 텍스트 파일내에 제목들은 어떤 문자를 사이에 두고 존재하는 지 궁금합니다. 예시를 보면 단순히 개행으로 각 제목을 구분한 것인지 혹은 두 개 이상의 개행을 이용한 것인지 헷갈려 질문드렸습니다.
Manager에 정의된 라빈 카프 함수의 경우, 하나의 문자열 속에서 찾고자 하는 문자열이 있는 지 검색하는 용도라고 이해했습니다. 이에 문자열 속 찾고자 하는 문자열 있다면 이를 알리기 위하여 bool 형 매개변수를 추가해도 되는 지 궁금합니다.


그 외

코드에는 ferr와 관련된 변수들이 존재하는 데, 제안서에서 이를 언급하지 않은 것 같습니다. 무시하고 프로젝트 진행하면 되나요?
스켈레톤 코드에 정의되지 않은 필드 변수들을 추가로 선언하여 사용하여도 되나요?
Manager 헤더에 min heap과 관련된 다익스트라 함수가 있는데 제안서에 해당 내용이 나와있지 않는 것 같습니다. 무시하고 구현하여도 되나요?
과제 제안서 5 페이지에 LOADREPORT 명령 사용법에 LOAD로 오타가 존재합니다.
과제 제안서 5 페이지에 DIJKSTRA 명령이 DIJKKSTRA로 작성되어있는 오타가 존재합니다.
과제 제안서 7페이지, 오류명 FaildtoUpdatePath에 오타가 존재하는 것 같습니다. 과제를 수행할 때는 FailedtoUpdataPath로 바꾸어 진행해도 되는 지 궁금합니다.
과제 제안서 7페이지 오류 코드를 나타내는 표에서 서로 다른 명령의 오류인 것 같은 오류들이 5번째 행에 하나인 것 처럼 표현되고 있습니다. InvalidAlgorithm의 경우 BFS, DIJKSTRA만의 오류, NegativeCycleDetected는 BELLMANFORD, FLOYD만의 오류라고 이해하면 되나요?
제공되는 텍스트 파일에 빈줄이 존재하는 경우가 있나요? 이런 경우 어떻게 처리해주어야 하나요?
추가적인 정보 없이 오류 메시지만을 출력하는 종류의 오류일 경우 다음과 같이 출력하면 되나요?
===== <오류명> =====
Error code: <오류 코드>
=================
한 명령의 출력을 마친 뒤에는 두 번 개행하는 지 궁금합니다. 또한 LOAD와 같이 오류메시지와 성공 메시지를 동시에 출력하는 명령의 경우 오류 메시지와 성공 메시지 사이도 두 번 개행하는 지 궁금합니다



질문 읽어주셔서 감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
