### ISSUE TITLE
음수인 간선이 존재할경우

### ISSUE THREAD

**Issue by chanseobx** [ghks4098/DS_Project_3_2021#4]
1. 음수인 간선이 존재할 경우

a)
![image](https://user-images.githubusercontent.com/90690557/141942965-92458d2e-ba49-4821-a52a-b0c3cc57d723.png)

b)
![image](https://user-images.githubusercontent.com/90690557/141943021-6d38188b-5997-40db-86b5-255e77a8ce2c.png)

a,b 둘 중 어느것으로 출력하나요?

2. pdf에 메모리관련 요구사항은 없던데 메모리 누수 검사를 하지 않나요?

**Comment by ghks4098** [comment]
log.txt 예시를 보시면 다음과 같이 있습니다.
 
 
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-16 (화) 16:43:25 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 음수인 간선이 존재할경우 (Issue #4)
 
예를들어 음수인 간선이 존재할 경우
=====================
Error code: 203
====== BFS ======
shortest path: 0 2 6
path length: 18
Course: Our Company ->Sonnet’s Ai Company ->Target Company
이거인가요?
아니면
====== BFS ======
Error code: 203
shortest path: 0 2 6
path length: 18
Course: Our Company ->Sonnet’s Ai Company ->Target Company
이거인가요?
전자로 하면 log.txt를 읽기가 너무 불편한 것 같습니다.
전자로 구현해야 하나요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
