### ISSUE TITLE
mapdata 질문입니다.

### ISSUE THREAD

**Issue by KiKi-Daehaksaeng** [ghks4098/DS_Project_3_2021#45]
edge의 weight가 숫자가 아닌 경우는 고려하지 않아도 되나요?

**Comment by ghks4098** [comment]
숫자가 아닌경우는 고려하지 않으셔도 됩니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-04 (토) 14:36:00 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] mapdata 질문입니다. (Issue #45)
 
edge의 weight가 숫자가 아닌 경우는 고려하지 않아도 되나요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
