### ISSUE TITLE
RABINKARP error code 질문

### ISSUE THREAD

**Issue by bjybs123** [ghks4098/DS_Project_3_2021#52]
![image](https://user-images.githubusercontent.com/63344843/144742137-e1bbc220-45b3-4435-a5bd-58811e284262.png)

![image](https://user-images.githubusercontent.com/63344843/144742150-de877709-dbda-454e-b297-7bb0c7cc0e5d.png)

![image](https://user-images.githubusercontent.com/63344843/144743117-93fd3cd4-a066-4041-ba6c-d39c93c3685a.png)

InvalidOptionNumber에 대한 enum이 정의가 안되어있는데 위 사진과같이 추가하면 되는것이 맞는지 궁금합니다

**Comment by ghks4098** [comment]
네 추가하셔서 사용하시면 될 것 같습니다.
-----Original Message-----
From: "Jiyong ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-05 (일) 19:07:57 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] RABINKARP error code 질문 (Issue #52)
 
InvalidOptionNumber에 대한 enum이 정의가 안되어있는데 위 사진과같이 추가하면 되는것이 맞는지 궁금합니다
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
