### ISSUE TITLE
텍스트 파일들에 질문있습니다.

### ISSUE THREAD

**Issue by quad0214** [ghks4098/DS_Project_3_2021#57]
안녕하세요. 컴퓨터정보공학부 2020202094학번 백종천입니다
 텍스트 파일들에 질문 있어 질문 작성했습니다.
 
 1. 아래에서 다른 분이 질문한 내용을 보면 모든 텍스트 파일은 두번의 개행으로 각 정보를 분리하는 것 같은데, 이전에 제가 한 질문에선는 텍스트 파일 내에 빈 줄이 존재하지 않는다고 답변해주셨습니다. 이에 세 번 이상의 개행이 없는 것이지 모든 데이터들은 다 두번의 개행으로 분리하는 것 맞나요? pdf 상 두 번 개행되어있는 것인지 한 번 개행 되어있는 것인 지 궁금하여 질문드렸습니다.

ex)

>  [command.txt]
>  LOAD a.txt
>  
>  PRINT
>  
>  BFS
>  
>  [mapdata.txt]
>  Our Company / 0 7
>  
>  Target Company / 2 0

 
 2. 리포트 파일의 경우 한번의 개행만 한 텍스트는 같은 제목 데이터라고 판단하나요?
 

> ex) 
> [reportdata.txt]
>  abcd
>  df
>    
>  edfg

>  위의 리포트 파일에서 a를 찾는 경우 abcd가 아니라
> abcd
> df
> 가 같은 제목 데이터로 판단되어 출력

   
3. log.txt에서 개행 횟수가 헷갈립니다.  다음과 같이 출력하는 것이 맞나요? 아니면 각 줄에 개행을 한 번 씩 더 해주어야 하나요?

> \=====LOAD=====
> Success
> \=============
> 
> \============
> Error code: 0
>\============

![image](https://user-images.githubusercontent.com/34961209/144793140-26b2682b-de00-4d93-ae58-4beddbec8b25.png)

 질문 읽어주셔서 감사합니다.

**Comment by ghks4098** [comment]
아 죄송합니다 
제가 코드 확인해보니까, report.txt파일내에서 한번의 개행으로 분리했습니다.
The cause of defects in apartment houses
Seoul Metropolitan Government's Big Data Promotion Project Survey Plan
Plans to promote the pet plant survey plan 
Public work projects in response to the COVID-19 incident
이런식으로요. mapdata.txt 파일에서도 마찬가지구요

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-06 (월) 14:39:21 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 텍스트 파일들에 질문있습니다. (Issue #57)
 
안녕하세요. 컴퓨터정보공학부 2020202094학번 백종천입니다
텍스트 파일들에 질문 있어 질문 작성했습니다.

아래에서 다른 분이 질문한 내용을 보면 모든 텍스트 파일은 두번의 개행으로 각 정보를 분리하는 것 같은데, 이전에 제가 한 질문에선는 텍스트 파일 내에 빈 줄이 존재하지 않는다고 답변해주셨습니다. 이에 세 번 이상의 개행이 없는 것이지 모든 데이터들은 다 두번의 개행으로 분리하는 것 맞나요? pdf 상 두 번 개행되어있는 것인지 한 번 개행 되어있는 것인 지 궁금하여 질문드렸습니다.
ex)
LOAD a.txt

PRINT
BFS
Our Company / 0 7
Target Company / 2 0

리포트 파일의 경우 한번의 개행만 한 텍스트는 같은 제목 데이터라고 판단하나요?
ex)
abcd
df

edfg
위의 리포트 파일에서 a를 찾는 경우 abcd가 아니라
abcd
df
가 같은 제목 데이터로 판단되어 출력
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by quad0214** [comment]
추가로 질문 있습니다. command.txt 파일의 경우에는 두번의 개행으로 각 명령어가 분리되어있는 것인가요?

**Comment by ghks4098** [comment]
command.txt도 한번의 개행으로 만드시면 될 것 같습니다.
 
-----Original Message-----
