### ISSUE TITLE
라빈카프알고리즘 질문

### ISSUE THREAD

**Issue by kwYoohae** [ghks4098/DS_Project_3_2021#6]
라빈카프알고리즘에서 pdf에 다음과 같은 예제가 있습니다.
![image](https://user-images.githubusercontent.com/74089271/142572790-474fdec9-0423-4249-9c0e-ab9facc06360.png)

이중에서 `RABINKARP surveyPlan`에 대한 결과가 다음과 같은데
![image](https://user-images.githubusercontent.com/74089271/142572852-15d5553f-95b8-4bf1-9776-3ae898ab1663.png)

다음과 같이 나와있는데 

라빈카프알고리즘에서 공백문자는 포함이기 때문에 해쉬값이 달라서 `survey plan`이라고 입력했을 때 이런결과가 나오고 
만약 `surveyPlan`인 경우 안나온다고 이해했는데 혹시 다른가요?

읽어주셔서 감사합니다.

**Comment by ghks4098** [comment]
아 네 맞습니다. survey plan 처럼 공백을 포함해서 검색을 하고
 surveyPlan인 경우 안나온다고 생각하신게 맞습니다.
그러하여 지금 깃허브의 pdf 파일을 survey plan이 공백을 포함해서 10글자가 넘어가서
예제를 Big data로 변경하였으니까 그 파일로 다시 보셔도 될 것 같습니다.  
 
-----Original Message-----
From: "Yoo ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-19 (금) 15:00:00 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 라빈카프알고리즘 질문 (Issue #6)
 
라빈카프알고리즘에서 pdf에 다음과 같은 예제가 있습니다.
이중에서 RABINKARP surveyPlan에 대한 결과가 다음과 같은데
다음과 같이 나와있는데
라빈카프알고리즘에서 공백문자는 포함이기 때문에 해쉬값이 달라서 survey plan이라고 입력했을 때 이런결과가 나오고
만약 surveyPlan인 경우 안나온다고 이해했는데 혹시 다른가요?
읽어주셔서 감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
