### ISSUE TITLE
플로이드 질문있습니다.

### ISSUE THREAD

**Issue by kwYoohae** [ghks4098/DS_Project_3_2021#60]
플로이드를 구현할 때 **IN_FINITY** 값을 넣는데

만약 음수간선이 존재하면 **IN_FINITY** 와 비교했을 때 더하면 예를들어 9999998의 값이나올 수도 있고
IN_FINITY로 놔둔 값이 갱신이 될 수 있습니다.

그런데 사실상 IN_FINITY라는 것은 끊어져있는 간선이 있는 경우라고 생각을 했습니다.

그래서 업데이트 된다는 것이 말이 안된다고 생각하는데 

혹시 이에 대해서 예외처리를 해주는 것이 맞는지 궁금합니다.

**Comment by ghks4098** [comment]
한번에 갈 수 없을때, 갱신 시키기 위해서 INFINITY가 들어있는 것이고, 
모든 노드는 결국에 서로 다 어떤 노드를 거쳐서든 다른노드를 갈 수 있는거 아닌가요,
무슨 말씀이신지 잘 모르겠습니다.
 
-----Original Message-----
From: "Yoo ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-06 (월) 20:56:31 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 플로이드 질문있습니다. (Issue #60)
 
플로이드를 구현할 때 IN_FINITY 값을 넣는데
만약 음수간선이 존재하면 IN_FINITY 와 비교했을 때 더하면 예를들어 9999998의 값이나올 수도 있고
IN_FINITY로 놔둔 값이 갱신이 될 수 있습니다.
그런데 사실상 IN_FINITY라는 것은 끊어져있는 간선이 있는 경우라고 생각을 했습니다.
그래서 업데이트 된다는 것이 말이 안된다고 생각하는데
혹시 이에 대해서 예외처리를 해주는 것이 맞는지 궁금합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kwYoohae** [comment]
@ghks4098 

`IN_FINITY`라는 값은 그래프 사이가 끊어져있을 때 즉 갈 수 없는 경우에 정한다고 생각을 했습니다

플로이드 알고리즘은 모든 path를 탐색하여 최적의 길을 찾아내는 알고리즘이지 않습니까?

조교님이 현재 말씀하신 `모든 노드는 결국에 서로 다 어떤 노드를 거쳐서든 다른노드를 갈 수 있는거 아닌가요?` 라는 말씀은

`IN_FINITY`라는 값으로 쓰여진 즉, 끊어져 있는 간선을 통해서도 갈 수 있다는 말씀이신가요?

현재 FLOYD를 돌리면 `IN_FINTY`의 값인 999999가 음수 간선이 있는경우 999998과 같이 갱신이 됩니다.

근데 끊어져있는 간선이기 때문에 갱신이 되면 안되는거 아닌가요?

이게 묻고싶은 바입니다.
