### ISSUE TITLE
bfs 최단경로 질문드립니다.

### ISSUE THREAD

**Issue by yebin-nnn** [ghks4098/DS_Project_3_2021#68]
bfs를 이용하여 최단 경로를 구할 때는 모든 간선의 가중치가 1인 것으로 생각하여, 가장 노드를 적게 거치는 경로가 구해진다고 알고 있습니다.

가중치가 있는 bfs의 최단 경로는 못구하지 않나요?
아니면 여기서 모든 간선의 가중치가 1이라고 가정하고, 경로를 구한 다음 path length를 계산해줘야 하나요?

**Comment by ghks4098** [comment]
인접노드 큐에 넣을때 큐에 들어갈때 한번 들어갔던 노드도 다시 넣어서 거리를 계산해서 bfs에서 비교하는 순서로 최단경로 비교를 하시면 될것 같습니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-07 (화) 18:31:13 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] bfs 최단경로 질문드립니다. (Issue #68)
 
bfs를 이용하여 최단 경로를 구할 때는 모든 간선의 가중치가 1인 것으로 생각하여, 가장 노드를 적게 거치는 경로가 구해진다고 알고 있습니다.
가중치가 있는 bfs의 최단 경로는 못구하지 않나요?
아니면 여기서 모든 간선의 가중치가 1이라고 가정하고, 경로를 구한 다음 path length를 계산해줘야 하나요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
잘 이해가 안가서 그런데, 방문했던 노드를 재방문해서 거리를 계산한다면 dijkstra와 다른점이 무엇인가요? 그냥 dijkstra를 queue로 구현하라는 말로 이해해도 되는건가요?

**Comment by ghks4098** [comment]
이미 정해진 최단경로를 이용하는 다익스트라와는 차이를 가지고 큐에 들어가거나 비교하게 될 것 같습니다.
 
-----Original Message-----
