### ISSUE TITLE
질문 있습니다.

### ISSUE THREAD

**Issue by Jae211** [ghks4098/DS_Project_3_2021#7]
1. vertex와 edge를 하나의 노드로 만들어 linked-list를 이용하여 연결해야 한다고 되어있는데, 각 node를 link할 때 각각 Edge, Vertex 클래스 내의 m_pNext를 사용하면 된다고 이해했습니다. 이것이 맞는지, 아니면 새로운 클래스를 생성하여 해당 클래스에 대한 포인터를 사용해야 하는 것인지 궁금합니다.
2. Vertex 클래스의 m_pEHead의 역할과 Edge 클래스의 m_key의 역할이 무엇인지 궁금합니다. m_key의 경우 m_weight와의 차이점이 궁금합니다.
3. 에러코드 중 200, 201번이 인자로 들어간 vertex 관련 에러코드인데, BFS, DIJKSTRA, BELLMANFORD는 모두 인자 없이 사용하는 명령어로 이해했습니다. 동작 예시의 BFS 1 3에 대한 에러 메시지처럼 각 명령어 뒤에 인자가 들어갈 경우 이 에러코드를 사용해야 하는 것인지 궁금합니다.

감사합니다.

**Comment by ghks4098** [comment]
1. 새로운 클래스를 만들어 포인터를 연결하는 식으로 구현하셔도 문제 없습니다.
 
2. 다음 vertex의 포인터를 연결해주는 역할이고, edge도 다음 edge를 연결해주는 pointer를 연결해주는 키와 weigth는 그 edge의 가중치를 나타내는 것 입니다.
 
3. 네 인자가 없는 명령어에서 인자가 들어온 경우 사용하시면 되는 에러코드 입니다.
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-19 (금) 21:41:31 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 질문 있습니다. (Issue #7)
 

vertex와 edge를 하나의 노드로 만들어 linked-list를 이용하여 연결해야 한다고 되어있는데, 각 node를 link할 때 각각 Edge, Vertex 클래스 내의 m_pNext를 사용하면 된다고 이해했습니다. 이것이 맞는지, 아니면 새로운 클래스를 생성하여 해당 클래스에 대한 포인터를 사용해야 하는 것인지 궁금합니다.
Vertex 클래스의 m_pEHead의 역할과 Edge 클래스의 m_key의 역할이 무엇인지 궁금합니다. m_key의 경우 m_weight와의 차이점이 궁금합니다.
에러코드 중 200, 201번이 인자로 들어간 vertex 관련 에러코드인데, BFS, DIJKSTRA, BELLMANFORD는 모두 인자 없이 사용하는 명령어로 이해했습니다. 동작 예시의 BFS 1 3에 대한 에러 메시지처럼 각 명령어 뒤에 인자가 들어갈 경우 이 에러코드를 사용해야 하는 것인지 궁금합니다.

감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
