### ISSUE TITLE
BFS, 다익스트라 음수 간선 질문

### ISSUE THREAD

**Issue by chb09876** [ghks4098/DS_Project_3_2021#70]
안녕하세요 조교님. 데이터구조 3차 프로젝트 질문드립니다.

BFS, 다익스트라 실행 시 음수 간선이 존재하면 해당 음수 간선을 "제거"하고 최단경로를 구한다고 제안서에 젹혀있는데,
그러면 음수 간선이 존재하는 그래프를 입력하고, 
BFS 또는 다익스트라 실행 후에는 그래프에 음수 간선이 존재하지 않는다고 생각하면 되나요?

BFS와 다익스트라에서 
그래프의 음수 간선 삭제가 맞는지, 아니면 음수 간선은 무시만 하고 그대로 그래프에 냅두는게 맞는지 궁금합니다.

**Comment by ghks4098** [comment]
음수 간선을 삭제하시고 결과를 돌리신게 출력되야하는 결과값이 되겠죠
bfs와 다익스트라가 정상 동작하는지 확인하고 싶은거라, 음수간선을 제거한걸 인풋으로 넣으셔도 될것같습니다.
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-07 (화) 18:57:35 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] BFS, 다익스트라 음수 간선 질문 (Issue #70)
 
안녕하세요 조교님. 데이터구조 3차 프로젝트 질문드립니다.
BFS, 다익스트라 실행 시 음수 간선이 존재하면 해당 음수 간선을 "제거"하고 최단경로를 구한다고 제안서에 젹혀있는데,
그러면 음수 간선이 존재하는 그래프를 입력하고,
BFS 또는 다익스트라 실행 후에는 그래프에 음수 간선이 존재하지 않는다고 생각하면 되나요?
BFS와 다익스트라에서
그래프의 음수 간선 삭제가 맞는지, 아니면 음수 간선은 무시만 하고 그대로 그래프에 냅두는게 맞는지 궁금합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chb09876** [comment]
감사합니다!
