### ISSUE TITLE
그래프에서 source - destination간 path가 존재하지 않을 경우

### ISSUE THREAD

**Issue by merryberry01** [ghks4098/DS_Project_3_2021#72]
그래프 내 source - destination간 path가 존재하지 않을 경우 어떤 에러 코드를 사용하면 되는지 궁금합니다.

**Comment by ghks4098** [comment]
그건 고려하지 않으셔도 될 것 같습니다
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-08 (수) 01:05:16 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 그래프에서 source - destination간 path가 존재하지 않을 경우 (Issue #72)
 
그래프 내 source - destination간 path가 존재하지 않을 경우 어떤 에러 코드를 사용하면 되는지 궁금합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
