### ISSUE TITLE
BFS 관련 질문입니다.

### ISSUE THREAD

**Issue by kwYoohae** [ghks4098/DS_Project_3_2021#76]
#68 번 이슈를 보고 질문 드립니다. 

현재 제가 알고있는 `BFS`라고 하는 알고리즘은 **가중치가 없는 상황에서 `최단 경로`를 구할 수 있는** 알고리즘으로 알고 있습니다.

그렇기 때문에 다음과 같은 예시 상황에서

`A -> E`까지의 거리를 구한다고 할 때

![image](https://user-images.githubusercontent.com/74089271/145213163-21c07ca0-c4cf-457f-81ca-a90d05c28bcf.png)

다음과 같이 가중치가 없는 경우 `A -> B -> E`를 구할 수 있습니다.

만약에 가중치가 있는 경우라도 `A -> B -> E`의 순서는 변하지 않을 것입니다.

`인접노드 큐에 넣을때 큐에 들어갈때 한번 들어갔던 노드도 다시 넣어서 거리를 계산해서 bfs에서 비교하는 순서로 최단경로 비교를 하시면 될것 같습니다.`

라고 언급하신 것을 보았습니다. 

첫 번째로는 만약 `한번 들어갔던 노드를 다시 넣어서 거리를 계산한다.` 라는 말씀은 `BFS`가 아닌 것 같습니다.

데이터 구조 설계 수업에서는 `BFS`를 할 경우 항상 `queue`에 넣는다고 하면 더이 상 방문할 수 있는 노드가 없는 경우 `POP`을 해주는 것으로 알고 있습니다.

또한, `BFS`는 애초에 가중치에 대해서 `Shortest path`를 구할 수 없는 알고리즘이기 때문에 

`BFS`를 통해서 구하는 `Shortest path`는 가중치가 없는 경우 방문할 수 있는 노드의 개수가 가장 짧은 방법이라고 저는 생각합니다.

위의 예제처럼 `A -> B -> E`를 통해서 최소 3번의 노드를 거쳐 방문할 수 있듯이 이것 또한, 거치는 최소의 노드의 개수를 일컫는 말인것 같습니다.

읽어주셔서 감사합니다.

**Comment by KiKi-Daehaksaeng** [comment]
동의합니다

**Comment by ghks4098** [comment]
임의의 방법으로라도 경로를 추적하여 가중치를 구해서 최단경리를 구하시면 됩니다
 
-----Original Message-----
From: "Yoo ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-12-08 (수) 15:37:30 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] BFS 관련 질문입니다. (Issue #76)
 
#63 번 이슈를 보고 질문 드립니다.
현재 제가 알고있는 BFS라고 하는 알고리즘은 가중치가 없는 상황에서 최단 경로를 구할 수 있는 알고리즘으로 알고 있습니다.
그렇기 때문에 다음과 같은 예시 상황에서
A -> E까지의 거리를 구한다고 할 때
다음과 같이 가중치가 없는 경우 A -> B -> E를 구할 수 있습니다.
만약에 가중치가 있는 경우라도 A -> B -> E의 순서는 변하지 않을 것입니다.
인접노드 큐에 넣을때 큐에 들어갈때 한번 들어갔던 노드도 다시 넣어서 거리를 계산해서 bfs에서 비교하는 순서로 최단경로 비교를 하시면 될것 같습니다.
라고 언급하신 것을 보았습니다.
첫 번째로는 인접노드 큐에 대한 말씀은 현재 구현하는 BFS는 Set이라는 STL을 이용해서 구현하는 것으로 알고 있습니다.
두 번째로는 만약 한번 들어갔던 노드를 다시 넣어서 거리를 계산한다. 라는 말씀은 BFS가 아닌 것 같습니다.
데이터 구조 설계 수업에서는 BFS를 할 경우 항상 queue에 넣는다고 하면 더이 상 방문할 수 있는 노드가 없는 경우 POP을 해주는 것으로 알고 있습니다.
또한, BFS는 애초에 가중치에 대해서 Shortest path를 구할 수 없는 알고리즘이기 때문에
BFS를 통해서 구하는 Shortest path는 가중치가 없는 경우 방문할 수 있는 노드의 개수가 가장 짧은 방법이라고 저는 생각합니다.
위의 예제처럼 A -> B -> E를 통해서 최소 3번의 노드를 거쳐 방문할 수 있듯이 이것 또한, 거치는 최소의 노드의 개수를 일컫는 말인것 같습니다.
읽어주셔서 감사합니다.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kwYoohae** [comment]
@ghks4098 `임의의 방법`이라는 소리가 무슨소리인지 잘 모르겠습니다.

설명해주실 수 있는 건가요? 

결론적으로는 `BFS`가 아닌 다른 방법으로 `BFS`의 최단 경로를 찾으라는 말씀이신가요?

**Comment by ghks4098** [comment]
인접한 노드를 우선 탐색하는 방법으로 최단경로를 찾으시면 될 것 같습니다.
 
-----Original Message-----

**Comment by kwYoohae** [comment]
@ghks4098 인접한 노드를 우선으로 라 는 말씀이 결론적으로는 그냥 `BFS`로 구현하고 

`BFS`를 구현할 때마다 weight를 보면서 다익스트라 처럼 최선의 탐색을 하지 않는다.

그래서 `queue`라고 하면 `Front`가 갈 수 있는 거리에 대해서 넣는거지 weight를 비교하는 것은 아니다 라는 말씀이신가요? 

결론적으로는 `BFS`로 구현하는 것은 맞는데 이는 가중치를 고려하지는 않는다 라는 말씀이신가요?

**Comment by kwYoohae** [comment]
@ghks4098 

아니면 `Greedy` 처럼 Front에서 `Weight`값을 비교하여 비교순으로 순서에 넣으라는 말인가요? 

그게 `shortest path`라는 말씀이신가요?

**Comment by ghks4098** [comment]
greedy하게 탐색해서 weight값을 비교하면 될 것 같습니다.
 
-----Original Message-----

**Comment by bjybs123** [comment]
> greedy하게 탐색해서 weight값을 비교하면 될 것 같습니다.
> […](#)
> -----Original Message----- From: "Yoo ***@***.***> To: ***@***.***>; Cc: ***@***.***>; ***@***.***>; Sent: 2021-12-08 (수) 22:14:07 (GMT+09:00) Subject: Re: [ghks4098/DS_Project_3_2021] BFS 관련 질문입니다. (Issue #76) @ghks4098 아니면 Greedy 처럼 Front에서 Weight값을 비교하여 비교순으로 순서에 넣으라는 말인가요? 그게 shortest path라는 말씀이신가요? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

@ghks4098 해당 부분은 제안서에 명시가 되어있지 않은 것으로 판단이 됩니다. 
다수의 학생들이 일반적인 weight를 고려하지 않은 BFS 알고리즘을 구현한 것으로 알고 있는데 
이 부분에 대해서 구현하지 못한다면 감점이 되는지 궁금합니다. 
감사합니다.

**Comment by ghost** [comment]
@ghks4098
말씀하신 모든 내용이 잘 이해가 가지 않아서 그런데, 조금만 더 자세히 설명해주실 수 있을까요?
queue에 넣기 전에 가장 weight가 작은 것을 넣은 형태로 하란 의미인가요?
현재 제안서 3page에는 "BFS 명령어는 Target 회사와의 경로와 거리를 구한다. 큐를 활용하여 구현한다. 큐에 넣는 순서는 회사들의 Index 순서대로 들어가야한다." 라고만 적혀있습니다.

**Comment by KiKi-Daehaksaeng** [comment]
혹시 홍철없는 홍철팀인가요?

**Comment by jiione** [comment]
@ghks4098  제가 이해하기론  BFS는  인접한 노드를 기준으로 Weight 상관없이 level이 가장 낮은 경로를 탐색하고, weight가 존재한다면 낮은 level의 정점이 최단 경로를 보장 할 수 없어 weight를 고려하지 않는 것으로 알고 있습니다.
 그래도 굳이 고려해야 한다면 BFS로 정점을 탐색 완료 하여도 다른 최단거리까지 고려하여 더 높은 레벨의 경로까지 탐색해야 하나요? 만약 그렇다면 다익스트라 알고리즘과 차이점이 궁금합니다.

**Comment by kwYoohae** [comment]
@ghks4098 

@bjybs123 분의 말씀에 첨언 하자면

`BFS`는 weight가 없는 상태에서 최단 경로를 구하는 알고리즘이다. 라는 정의에 의해서 혼동이 온것 같습니다.

`BFS`를 구현할 때에는 애초에 **weight**가 없을 때 최단 경로를 구하니까 

제안서에서 상세하게 설명이 빠져있어서 **weight**가 없을 때를 생각하여 
 weight를 비교해가면서가 아닌 순서대로 `queue`에 집어넣은 형태로 구현을 한 것 같습니다

현재 과제 마감까지 별로남지 않은 상황입니다. 

혹시 이러한 부분에 대해서 `Greedy` 하지 않게 구현을 한다면 감점이 있는지 궁금합니다

읽어주셔서 감사합니다

**Comment by 6Whistle** [comment]
기본적으로 수업에서 배운 bfs 알고리즘과 다를 뿐만 아니라 제안서에도 기본적인 bfs 알고리즘을 구현하라고 명시되어있습니다. 해당 부분에 대한 말씀하신 부분이 제안서에 없었을 뿐더러 과제 제출 3일 전에 해당 부분에 대한 답변이 진행된 것은 충분히 문제가 될 것 같아 보입니다.

**Comment by ghks4098** [comment]
이런 부분에서 문제가 있다고 생각되어서
BFS 구현에서 감점이 없을 예정입니다.
 
 
-----Original Message-----

**Comment by ghks4098** [comment]
weight를 고려하지 않고 BFS 구현하시면 감점은 없을 예정입니다
 
 
-----Original Message-----

**Comment by kwYoohae** [comment]
@ghks4098 감사합니다
