### ISSUE TITLE
질문 있습니다.

### ISSUE THREAD

**Issue by chanseobx** [ghks4098/DS_Project_3_2021#8]
경로를 나타낼 배열, weight를 나타낼 배열을 따로 만들지 않고
tuple.h을 이용해서 하나의 벡터안에 weight,방문/미방문,경로 를 나타낼 수 있게 구현했는데

tuple.h을 사용해도 괜찮을까요?

**Comment by ghks4098** [comment]
네 튜플 사용해도 상관없습니다.
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-20 (토) 12:05:20 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 질문 있습니다. (Issue #8)
 
경로를 나타낼 배열, weight를 나타낼 배열을 따로 만들지 않고
tuple.h을 이용해서 하나의 벡터안에 weight,방문/미방문,경로 를 나타낼 수 있게 구현했는데
tuple.h을 사용해도 괜찮을까요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
