### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by KiKi-Daehaksaeng** [ghks4098/DS_Project_3_2021#9]
1.
![image](https://user-images.githubusercontent.com/76834414/142729548-e61a511a-df65-40b2-8d8e-8b52558d723e.png)
find계열 명령어로 경로를 탐색할 때 회사 이름에 있는 띄어쓰기는 없애야합니까?

2.
![image](https://user-images.githubusercontent.com/76834414/142729717-e59111cd-8bfb-459e-8cdf-b4cdf1f77e50.png)

거리 정보 데이터가 존재하지 않을 경우의 예외는 202로 되어있는데, 보고서 제목 데이터가 없는 경우의 예외는 따로 없습니다. 이때는 어떻게 해야하나요?

**Comment by ghks4098** [comment]
1. 띄어쓰기는 포함해야 합니다.
 
2. 기본적으로 없는 에러는 구현에 대한 감점은 없을 예정이구요, 동일하게 202로 처리해주시면 될 것 같습니다.
 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-20 (토) 23:22:42 (GMT+09:00)
Subject: [ghks4098/DS_Project_3_2021] 질문있습니다. (Issue #9)
 




find계열 명령어로 경로를 탐색할 때 회사 이름에 있는 띄어쓰기는 없애야합니까?



거리 정보 데이터가 존재하지 않을 경우의 예외는 202로 되어있는데, 보고서 제목 데이터가 없는 경우의 예외는 따로 없습니다. 이때는 어떻게 해야하나요?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
